
spring:
  application:
    name: cloud-native-spring
  profiles:
    active: dev
 # config:
    #import: configserver:http://localhost:8888
    #use-legacy-processing: true

    
server.port: 8080


management:
  endpoints:
    web:
      exposure:
        include: '*'
        


cook.special: "Kim Chi in cloud-native-spring app"
